name: nature_remo
description: A Nature Remo Cloud And Local API Client that uses Nature API 1.0.0.
version: 0.4.1
homepage: https://github.com/futabooo/nature-remo-dart

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  http: ^1.4.0
  collection: ^1.19.1

dev_dependencies:
  test: ^1.16.0
  lints: ^6.0.0